name: 1st Workflow
on:
  - push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files and Copy Repo
        run: |
          pwd
          ls -a
      - uses: actions/checkout@v4
      - name: List Files
        run: ls -a